package vistas;

import javax.swing.JOptionPane;
import modelo.Tarea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author olive
 */
public class bienvenido extends javax.swing.JFrame {

    /**
     * Creates new form bienvenido
     */
    public bienvenido() {
        initComponents();
        this.setLocationRelativeTo(null);
        jpanel_agregar.setVisible(false);
        jpanel_eliminar.setVisible(false);
        jpanel_filtrar.setVisible(false);
        jpanel_modificar.setVisible(false);
        jpanel_mostrar.setVisible(false);        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelicon = new javax.swing.JLabel();
        jButtonAgregarTarea = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jButtonFiltrar = new javax.swing.JButton();
        jpanel_agregar = new javax.swing.JPanel();
        jpanel_eliminar = new javax.swing.JPanel();
        jpanel_modificar = new javax.swing.JPanel();
        jpanel_mostrar = new javax.swing.JPanel();
        jpanel_filtrar = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png.png"))); // NOI18N

        jButtonAgregarTarea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAgregarTarea.setText("Agregar Tarea");
        jButtonAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTareaActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar Tarea");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonModificar.setText("Modificar Tarea");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonMostrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMostrar.setText("Mostrar Tarea");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonFiltrar.setText("Filtrar Tarea");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarTarea)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonModificar)
                    .addComponent(jButtonMostrar)
                    .addComponent(jLabelicon)
                    .addComponent(jButtonFiltrar))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelicon)
                .addGap(34, 34, 34)
                .addComponent(jButtonAgregarTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFiltrar)
                .addGap(39, 39, 39))
        );

        jpanel_agregar.setBackground(new java.awt.Color(153, 204, 255));

        jpanel_eliminar.setBackground(new java.awt.Color(153, 204, 255));

        jpanel_modificar.setBackground(new java.awt.Color(153, 204, 255));

        jpanel_mostrar.setBackground(new java.awt.Color(153, 204, 255));

        jpanel_filtrar.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpanel_filtrarLayout = new javax.swing.GroupLayout(jpanel_filtrar);
        jpanel_filtrar.setLayout(jpanel_filtrarLayout);
        jpanel_filtrarLayout.setHorizontalGroup(
            jpanel_filtrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        jpanel_filtrarLayout.setVerticalGroup(
            jpanel_filtrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanel_mostrarLayout = new javax.swing.GroupLayout(jpanel_mostrar);
        jpanel_mostrar.setLayout(jpanel_mostrarLayout);
        jpanel_mostrarLayout.setHorizontalGroup(
            jpanel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_mostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_filtrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_mostrarLayout.setVerticalGroup(
            jpanel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_mostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_filtrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanel_modificarLayout = new javax.swing.GroupLayout(jpanel_modificar);
        jpanel_modificar.setLayout(jpanel_modificarLayout);
        jpanel_modificarLayout.setHorizontalGroup(
            jpanel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_modificarLayout.setVerticalGroup(
            jpanel_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_modificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_mostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpanel_eliminarLayout = new javax.swing.GroupLayout(jpanel_eliminar);
        jpanel_eliminar.setLayout(jpanel_eliminarLayout);
        jpanel_eliminarLayout.setHorizontalGroup(
            jpanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_eliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanel_eliminarLayout.setVerticalGroup(
            jpanel_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanel_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanel_agregarLayout = new javax.swing.GroupLayout(jpanel_agregar);
        jpanel_agregar.setLayout(jpanel_agregarLayout);
        jpanel_agregarLayout.setHorizontalGroup(
            jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_agregarLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jpanel_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpanel_agregarLayout.setVerticalGroup(
            jpanel_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanel_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpanel_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jpanel_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jButtonSalir)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
       String titulo = JOptionPane.showInputDialog("Ingrese el título de la tarea:"); 
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTareaActionPerformed
          String titulo = JOptionPane.showInputDialog("Ingrese el título de la tarea:");
    String descripcion = JOptionPane.showInputDialog("Ingrese la descripción de la tarea:");
    String fechaLimite = JOptionPane.showInputDialog("Ingrese la fecha límite (dd/mm/aaaa):");
    String estado = JOptionPane.showInputDialog("Ingrese el estado (por hacer, en progreso, completada):");
    int prioridad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la prioridad (1-5):"));

    Tarea nuevaTarea = new Tarea(titulo, descripcion, fechaLimite, estado, prioridad);

    // Preguntar si desea agregar etiquetas
    String respuesta = JOptionPane.showInputDialog("¿Desea agregar etiquetas a esta tarea? (Si/No):");
    if (respuesta != null && respuesta.equalsIgnoreCase("Si")) {
        boolean agregarMasEtiquetas = true;
        while (agregarMasEtiquetas) {
            String etiqueta = JOptionPane.showInputDialog("Ingrese la etiqueta:");
            nuevaTarea.setEtiqueta(etiqueta);
            respuesta = JOptionPane.showInputDialog("¿Desea agregar otra etiqueta? (Si/No):");
            if (respuesta == null || !respuesta.equalsIgnoreCase("Si")) {
                agregarMasEtiquetas = false;
            }
        }
    }

    // Aquí puedes hacer lo que quieras con la nueva tarea, como guardarla en una lista, base de datos, etc.
    // Ejemplo: listaTareas.add(nuevaTarea);

    // Mostrar un mensaje indicando que la tarea ha sido agregada correctamente
    JOptionPane.showMessageDialog(this, "Tarea agregada correctamente.");
    }//GEN-LAST:event_jButtonAgregarTareaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String titulo = JOptionPane.showInputDialog("Ingrese el título de la tarea:");
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        String titulo = JOptionPane.showInputDialog("Ingrese el título de la tarea:"); 
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
  String titulo = JOptionPane.showInputDialog("Ingrese el título de la tarea:");
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bienvenido().setVisible(true);
            }
        });
    }//ese panel pero solo es para agregar no? si quiero que caba bton tenga su panel tiene que tener un panel individual? lo agregar a cada boton individualmente y los otros los vuelves invisibles

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTarea;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpanel_agregar;
    private javax.swing.JPanel jpanel_eliminar;
    private javax.swing.JPanel jpanel_filtrar;
    private javax.swing.JPanel jpanel_modificar;
    private javax.swing.JPanel jpanel_mostrar;
    // End of variables declaration//GEN-END:variables
}
