package vistas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author olive
 */
import java.util.*;
import javax.swing.JOptionPane;
import modelo.*;
        
        
public class registro extends javax.swing.JFrame {

    /**
     * Creates new form registro
     */
    public registro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        cancelarbtn = new javax.swing.JButton();
        registrarbtn = new javax.swing.JButton();
        jLabelGmail = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        nombretxt = new javax.swing.JTextField();
        gmailtxt = new javax.swing.JTextField();
        usuariotxt = new javax.swing.JTextField();
        contraseñatxt = new javax.swing.JPasswordField();
        jLabelicon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jPanel2.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 218, -1, -1));

        cancelarbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelarbtn.setText("Cancelar");
        cancelarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(cancelarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 417, 135, -1));

        registrarbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registrarbtn.setText("Registrar");
        registrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarbtnActionPerformed(evt);
            }
        });
        jPanel2.add(registrarbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 378, 135, -1));

        jLabelGmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelGmail.setText("Gmail:");
        jPanel2.add(jLabelGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 258, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsuario.setText("Nombre Usuario:");
        jPanel2.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 298, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña:");
        jPanel2.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 338, -1, -1));
        jPanel2.add(nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 218, 156, -1));
        jPanel2.add(gmailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 258, 156, -1));
        jPanel2.add(usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 298, 158, -1));
        jPanel2.add(contraseñatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 338, 158, -1));

        jLabelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/png.png"))); // NOI18N
        jPanel2.add(jLabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 41, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//ya se registra y guarda, falta que recupere ese dato caudno se apreta iniciar es afuncion de contraseña para que es ? es la que se crea por defecto el boton
    private void registrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarbtnActionPerformed
        String nombre = nombretxt.getText();
        String gmail = gmailtxt.getText();
        String usuario = usuariotxt.getText();
        String contra = contraseñatxt.getText();
         
        if(nombre.isEmpty()|| gmail.isEmpty()|| usuario.isEmpty()|| contra.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos para el registro");
        }else{
        Usuario nuevo = new Usuario(nombre,gmail,usuario, contra);
        GestorUsuarios.registrarUsuario(nuevo);
        dispose();
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.show();
        }
    }//GEN-LAST:event_registrarbtnActionPerformed

    private void cancelarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarbtnActionPerformed
        dispose();
        Menu menu = new Menu();
        menu.setLocationRelativeTo(null);
        menu.show();
    }//GEN-LAST:event_cancelarbtnActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarbtn;
    private javax.swing.JPasswordField contraseñatxt;
    private javax.swing.JTextField gmailtxt;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelGmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelicon;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombretxt;
    private javax.swing.JButton registrarbtn;
    private javax.swing.JTextField usuariotxt;
    // End of variables declaration//GEN-END:variables
}
